### Prueba
POST http://localhost:8000/api/v1/ai/ask
Content-Type: application/json

{
    "question": "Hola que tal!!, dame informacion sobre precios de ceremonia de bodas",
    "document": null,
    "image": null
}


### Prueba de eliminacion
POST http://localhost:8000/api/v1/ai/clearfiles
Content-Type: application/json

{
    
}


### Prueba de eliminacion
GET http://localhost:8000/api/v1/ai/files
Content-Type: application/json

{
    
}

### Historial
GET http://localhost:8000/api/v1/ai/history/session_default
Content-Type: application/json

{
    
}